config/routes.rb
Tshirt::Application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :authentications

  root to: 'home#index'
  get "/designs/:product_id", :to => "designs#index", :as => "designs"
  get "/designs", :to => "designs#index", :as => "designs"
  get "/design_categories", :to => "designs#category", :as => "design_category"
  post "/save_user_images", :to => "designs#save_user_images"
  get "/contact", :to => "home#new_contact", :as => "contact"
  post "/contact", :to => "home#create_contact", :as => "contact_us"
  get "/about_us", :to => "home#about_us", :as => "about"
  get "/partners", :to => "home#partners", :as => "partners"
  get "/how_to_design", :to => "home#how_to_design", :as => "how_to_design"
  get "/how", :to => "home#how", :as => "how"
  get "/checkout", :to => "orders#new_checkout", :as => "checkout"
  get "/get_product", :to => "products#get_product", :as => "get_product"
  get "/products", :to => "products#products", :as => "product"
  post "/calculation", :to => "products#calculation"
  post "/save_item", :to => "orders#save_item"
  resources :categories
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
  controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  match '/auth/:provider/callback' => 'authentications#create'
  get "/terms_and_conditions", :to => "home#terms_and_conditions"
  get "/privacy_policy", :to => "home#privacy_policy"
  get "/legal_terms", :to => "home#legal_terms"
  get "/user_settings", :to => "home#user_settings", :as => "user_setting"

  get "get_design", :to => "orders#get_design"
  match "/profile_billing", :to => "home#create_billing", :as => "profile_billing"
  match "/profile_shipping", :to => "home#create_shipping", :as => "profile_shipping"
  match "/save_user", :to => "home#save_user", :as => "save_user"
  match "/change_password", :to => "home#change_password", :as => "change_password"
  match "/email_avail", :to => "home#email_avail", :as => "email_avail"
  match "/delete_user_product/:id", :to => "home#delete_user_product", :as => "delete_user_product"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user! , :only => [:user_settings]
	def index
		@sliders = Slider.where(:status => true)
	end
	
	def sign_in
	end
	
	def new_contact
		@contact = Contact.new  
	end
	
	def create_contact
		@contact = Contact.new(params[:contact])
		respond_to do |format|
			if(UserMailer.contact_email(params[:contact]).deliver  && @contact.save)
				format.html {redirect_to(contact_path(), :notice => "Message sent successfully")}   
			else
				format.html {redirect_to(contact_path(), :notice => "Please fill in all fields with valid values and submit")}   
				#format.html { render :action => "new_contact", :notice => "Please fill all fields and send"}
			end
		end
	end
	
	def about_us
	end
	
	def partners
	end

	def terms_and_conditions
	end
	
	def how_to_design
	end

	def how
	end

	def legal_terms
	end

	def create_billing
		current_user.create_billing_address(params[:billing_address])   
		redirect_to user_setting_path()
	end
	def create_shipping
		current_user.create_shipping_address(params[:shipping_address])   
		redirect_to user_setting_path()
	end

	def save_user
		current_user.update_attributes(:email => params[:user][:email],:first_name => params[:user][:first_name],:last_name => params[:user][:last_name],:mobile => params[:user][:mobile])   
		redirect_to user_setting_path()
	end
	def delete_user_product
		@user_items = UserItem.find_by_id(params[:id]).delete()
		redirect_to user_setting_path()
	end
	def change_password
		current_user.update_attributes(:password => params[:user][:password],:password_confirmation => params[:user][:password_confirmation])   
		if(params[:user][:password].present?)
			redirect_to new_user_session_path, :notice => "Please login with changed password"
		else
			redirect_to user_setting_path()
		end
	end


	def email_avail
		if User.exists?(:email=>params[:email])
			msg = "Email not available"
		else
			msg = ""
		end
		respond_to do |format|
			format.json {render :json => {:msg => msg}}
			format.js
			format.html
		end
	end
	def user_settings
		@user = current_user
		@billing = @user.billing_address.present? ? @user.billing_address : @user.build_billing_address
		@shipping = @user.shipping_address.present? ? @user.shipping_address : @user.build_shipping_address
		@category = Category.all
		@user_items = @user.user_items
		# if(params[:category_id].present?)
		# 	@products = Product.where(:category_id => params[:category_id])
		# else
		# 	@products = Product.all
		# end
		respond_to do |format|
			format.json {render :json => {:products => @products}}
			format.js
			format.html
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
<%= stylesheet_link_tag  "about-us", :media => "all" %>
<%= raw t(:about_us_content)%>
<!-- <section class="about-us">
	<div class="center-details">
		<div class="details">
			<div class="head">Hola, yo soy Mobby,</div>
			<p>Somos una startup especializada en márketing digital.</p>
			<p>Creemos verdaderamente que el márketing y el diseño  son la energia que mueve tu marca, negocio o concepto.</p>
			<div class="title">El secreto de Mobby es: </div>
			<ul class="tick-list-black">
				<li>hazlo interactivo</li>
				<li>hazlo divertido</li>
				<li>hazlo intuitivo</li>
				<li>haz que los usuarios quieran regresar</li>
			</ul>
		</div>
		<div class="details">
			<div class="head">Powered by Mobby</div>
			<div class="title">Algunas de nuestras platformas:</div>
			<p>
				<b>Mobbynet:</b> Red Social alrededor de compras, eventos y ofertas.
				HTML5 y webapps.
			</p>
			<p>
				<b>Mobby2go:</b> Programa móvil de fidelidad para smartphones. Android and Blackberry
			</p>
			<p>
				<b>Chat4:</b> App para chatear con recompensas. Android y Blackberry
			</p>
			<p>
			<b>Drink4:</b> Ordena con tu móvil comida y bebidas con recompensas y programa de fidelidad para la hosteleria. Android y Apple
			</p>
		</div>
	</div>
</section> -->

app/views/home/how.html.erb
<%= stylesheet_link_tag  "how", :media => "all" %>
<%= stylesheet_link_tag  "how-to-design", :media => "all" %>
	<section class="how-page">
		<div class="container">
			<div class="center">
				<div class="logo">
					<img src="/assets/logoa.png">
				</div>
				<div class="arrows">
					<img class="green" src="/assets/how/arrow-green.png">
					<img class="violet" src="/assets/how/arrow-violet.png">
					<img class="blue" src="/assets/how/arrow-blue.png">
					<img class="brown" src="/assets/how/arrow-brown.png">
					<img class="c-green" src="/assets/how/arrow-c-green.png">
				</div>
				<%= raw t(:how_circle) %>
				<%= raw t(:how_to_design) %>
				<!-- <div class="circles">
					<div class="green circle">
						<div class="small-icon bg"><img src="/assets/how/icon-green.png"></div>
						<div class="content bg">
							<div class="name">Hotel Merchanidise</div>
						</div>
						<div class="title bg">Sell to your guest</div>
					</div>
					<div class="violet circle">
						<div class="small-icon bg"><img src="/assets/how/icon-violet.png"></div>
						<div class="content bg">
							<div class="name">City Merchandise</div>
						</div>
						<div class="title bg">City visual Impact</div>
					</div>
					<div class="blue circle">
						<div class="small-icon bg"><img src="/assets/how/icon-blue.png"></div>
						<div class="content bg">
							<div class="name">Event Merchandise</div>
						</div>
						<div class="title bg">For upcoming events</div>
					</div>
					<div class="brown circle">
						<div class="small-icon bg"><img src="/assets/how/icon-brown.png"></div>
						<div class="content bg">
							<div class="name">Organisation Merchandise</div>
						</div>
						<div class="title bg">Build team strength</div>
						</div>
						<div class="c-green circle">
							<div class="small-icon bg"><img src="/assets/how/icon-c-green.png"></div>
							<div class="content bg">
								<div class="name">Business Merchandise</div>
							</div>
							<div class="title bg">Your brand at clients home</div>
						</div>
					</div>
				</div> -->
				<!-- <div class="circles">
					<div class="green circle">
						<div class="small-icon bg"><img src="/assets/how/icon-green.png"></div>
						<div class="content bg">
							<div class="name">Hotel Merchanidise</div>
						</div>
						<div class="title bg">Vende a su huésped</div>
					</div>
					<div class="violet circle">
						<div class="small-icon bg"><img src="/assets/how/icon-violet.png"></div>
						<div class="content bg">
							<div class="name">Mercancía<br>City</div>
						</div>
						<div class="title bg">Ciudad de impacto visual</div>
					</div>
					<div class="blue circle">
						<div class="small-icon bg"><img src="/assets/how/icon-blue.png"></div>
						<div class="content bg">
							<div class="name">Mercancía Evento</div>
						</div>
						<div class="title bg">Para los próximos eventos</div>
					</div>
					<div class="brown circle">
						<div class="small-icon bg"><img src="/assets/how/icon-brown.png"></div>
						<div class="content bg">
							<div class="name">Organización Merchandise</div>
						</div>
						<div class="title bg">Construir la fuerza del equipo</div>
						</div>
						<div class="c-green circle">
							<div class="small-icon bg"><img src="/assets/how/icon-c-green.png"></div>
							<div class="content bg">
								<div class="name">Mercancía Negocio</div>
							</div>
							<div class="title bg">Su marca a los clientes en casa</div>
						</div>
					</div>
				</div> -->
			</div>
		</div>
	</section>

app/views/home/how_to_design.html.erb
<%= stylesheet_link_tag  "how-to-design", :media => "all" %>
<%= raw t(:how_to_design) %>

<!-- 
<section class="how-to-design">
	<div class="container">
		<div class="section-title">Tus productos personalizados para merchandise y
			márketing diseñados por ti</div>
			<div class="section-details">
				<p>
					Ahora puedes crear productos de márketing que mostrará tu marca luego que tus clientes o amigos hayan visitado tu negocio, hotel, festival, fiesta, y más.
				</p>
				<p>
					Usa nuestros diseños exclusivos para crear merchandise que puedes vender, regalar o usar y que convierte a ese momento en muy especial.
				</p>
			</div>
			<div class="how-it-work">
				<div class="title">Como funciona?</div>
				<div class="steps">
					<div class="step">
						<div class="img-holder"><img src="/assets/crew_front.png"></div>
						<div class="about">
							<span class="count">1</span>
							<span>Selecciona tu producto. Déjanos saber si no encuentras el producto que deseas.</span>
						</div>
					</div>
					<div class="step">
						<div class="img-holder make-center"><img src="/assets/cartoon.jpg"></div>
						<div class="about">
							<span class="count">2</span>
							<span>Seleciona nuestro diseño, o sube tu propia imagen (preferimos imágenes vectorizadas)</span>
						</div>
					</div>
					<div class="step">
						<div class="img-holder"><img src="/assets/tshirt-hotel.png"></div>
						<div class="about">
							<span class="count">3</span>
							<span>Comienza a diseñar! Agrega tu texto, nombre, marca, negocio o evento y personalizalo</span>
						</div>
					</div>
				</div>
			</div>
			<div class="customize-it">
				<div class="title">Personalizalo</div>
				<div class="intro">
					<div class="about">
						Con nuestra herramienta de diseño online puedes personalizar tus productos exactamente como lo desees. Cuando hayas terminado seimprimirá
					</div>
					<div class="img-holder">
						<img src="/assets/editor-image.png">
					</div>
				</div>
				<div class="tags">
					<div class="tag1">
						<span>Tu marca</span>
					</div>
					<div class="tag2">
						<span>Tu lugar</span>
					</div>
					<div class="tag3">
						<span>Tu merchandise</span>
					</div>
				</div>
				<div class="product-details">
					<img class="product-img" src="/assets/tshirt-hotel-text.png">
					<div class="add-name">
						Agrega tu texto
						<img src="/assets/pointer-gallery.png">
					</div>
					<div class="add-img">
						Agrega nuestros diseños exclusivos o usa tus propias imágenes, o te crearemos un diseño exclusivo para ti
						<img src="/assets/pointer-interface.png">
					</div>
					<div class="add-text">
						Agrega cualquier texto, lugar, números, nombres, etc.
						<img src="/assets/pointer-templates.png">
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

 -->

app/views/home/index.html.erb
<%= stylesheet_link_tag  "index", "slider/style", :media => "all" %>
<%= javascript_include_tag  "slider/jquery-1.6.2.min", "slider/jquery.easing.1.3", "slider/style", "slider/jquery.mousewheel", "slider/jquery.contentcarousel"  %>
<!--  -->
<%= raw t :index %>

<!-- changed for language -->
<!-- <section class="banner"> 
	<div class="container"> 
		<div class="slider"> 
			<div class="desc gallery"> 
				<div class="desc-head"> 
					<i class="banner-icon"></i>
					Creación de productos personalizados 
				</div> 
				<div class="desc-value">
					Para marketing, promociones y merchandising 
				</div> 
				<img class="pointer" src="assets/1.png"> 
			</div> 
			<div class="desc templates"> 
				<div class="desc-head"> 
					<i class="banner-icon"></i>
					Utilice nuestro ilustraciones exclusivas 
				</div> 
				<div class="desc-value">
					O cargar sus propias imágenes 
				</div> 
				<img class="pointer" src="assets/3.png"> 
			</div> 
			<div class="desc interface"> 
				<div class="desc-head"> 
					<i class="banner-icon"></i>
					Personalizar yout camiseta 
				</div> 
				<div class="desc-value">
					Para eventos, bodas, fiestas, equipos y más 
				</div> 
				<img class="pointer" src="assets/2.png"> 
			</div> 
			<div class="center-image"> 
				<div id="myCarousel" class="carousel slide"> 
					<ol class="carousel-indicators"> 
						<li data-target="#myCarousel" data-slide-to="0" class="active"> 
						</li> 
						<li data-target="#myCarousel" data-slide-to="1"> 
						</li> 
						<li data-target="#myCarousel" data-slide-to="2"> 
						</li> 
					</ol> 
					<div class="carousel-inner"> 
						<div class="active item"> 
							<img src="/assets/center-image.png"> 
						</div> 
						<div class="item"> 
							<img src="/assets/center-image.png"> 
						</div> 
						<div class="item"> 
							<img src="/assets/center-image.png"> 
						</div> 
					</div> 
					<a class="carousel-control left" href="#myCarousel" data-slide="prev"> 
						<img src="/assets/prev.png"> 
					</a> 
					<a class="carousel-control right" href="#myCarousel" data-slide="next"> 
						<img src="/assets/next.png"> 
					</a> 
				</div> 
			</div> 
		</div> 
	</div> 
</section> 
<section class="testimonials"> 
	<div class="container"> 
		<p>
			Crea tus productos personalizados de 
			<br> Marketing, Promociones y mercancía 
		</p> 
	</div> 
</section> 
<section class="process-steps hi-icon-effect-9 hi-icon-effect-9a"> 
	<div class="container"> 
		<div class="row"> 
			<div class="span4 choose-design"> 
				<a href="" class="hi-icon "> 
					<img src="assets/design-icon.png"> 
				</a> 
				<p class="title">
					Nuestros diseños exclusivos 
				</p> 
			</div> 
			<div class="span4 add-photo"> 
				<a href="" class="hi-icon "> 
					<img src="assets/photo-icon.png"> 
				</a> 
				<p class="title">
					Tus propias imágenes 
				</p> 
			</div> 
			<div class="span4 save-icon"> 
				<a href="" class="hi-icon "> 
					<img src="assets/save-icon.png"> 
				</a> 
				<p class="title">
					Diseño e impresión 
				</p> 
			</div> 
		</div> 
	</div> 
</section> -->
<!-- changed for language -->

<section class="images"> <div class="container">
	<div id="ca-container" class="ca-container featured-slider">
		<div class="ca-wrapper">
			<% @sliders.each_with_index do |slider ,index|%>
			<div class="ca-item ca-item-<%=index%>">
				<img src="<%= slider.image.url%>">
			</div>

			<% end %>
				<!-- <div class="ca-item ca-item-1">
					<img src="assets/ts1.png">
				</div>
				<div class="ca-item ca-item-2">
					<img src="assets/ts2.png">
				</div>
				<div class="ca-item ca-item-3">
					<img src="assets/ts3.png">
				</div>
				<div class="ca-item ca-item-4">
					<img src="assets/ts4.png">
				</div>
				<div class="ca-item ca-item-5">
					<img src="assets/ts2.png">
				</div>
				<div class="ca-item ca-item-6">
					<img src="assets/ts3.png">
				</div> -->
			</div>
		</div>
	</div>
</section>

<script type="text/javascript">
	$(document).ready(function() {
		if($('#ca-container .ca-item').length>4){
			$('#ca-container').contentcarousel();
		}
		$('.carousel').carousel()

	});

</script>

app/views/home/new_contact.html.erb
<%= stylesheet_link_tag  "contact-us", :media => "all" %>

<!-- <%=raw t(:contact_us_left_side) %> -->
<section class="contact-us">
	<div class="container">
		<div class="row">
			<div class="span4 left-side">
				<%=raw t(:contact_us_left_side) %>
				<!-- <img class="left-mark" src="/assets/left-mark.png">
				<p class="title">We would love to hear from you</p>
				<p class="sub-title">Please contact us  with any questions about:</p>
				<ul class="">
					<li><img src="/assets/list-tick-gray.png"> &nbsp;Design</li>
					<li><img src="/assets/list-tick-gray.png"> &nbsp;Shipping</li>
					<li><img src="/assets/list-tick-gray.png"> &nbsp;Products</li>
					<li><img src="/assets/list-tick-gray.png"> &nbsp;Partnership</li>
					<li><img src="/assets/list-tick-gray.png"> &nbsp;Suggestions</li>
					<li><img src="/assets/list-tick-gray.png"> &nbsp;Comments Feedback</li>
				</ul> -->
			</div>
			<div class="span8 right-side">
				<div class="contact-box span6">
					<%= simple_form_for @contact, :url => contact_us_path do |f| %>
					<img src="/assets/send-msg-corner.png" class="corner">
					<div class="title"><%= t(:send_us_a_msg) %></div>
					<div class="underline"></div>
					<%= f.text_field :name, :class=>"name", :placeholder =>t(:enter_your_name) %>
					<%= f.text_field :email, :class=>"email", :placeholder =>t(:enter_your_email) %>
					<%= f.text_area :message, :class=>"message", :placeholder =>t(:enter_your_message) %>
					<div class="follow-us">
						<a class="social-gplus" href="#"></a>
						<a class="social-in" href="#"></a>
						<a class="social-rss" href="#"></a>
						<a class="social-fb" href="#"></a>
						<%= f.button :submit, :class=>"btn btn-danger pull-right", :value=>t(:send_msg) %>
					</div>
					<% end %>
				</div>
			</div>
		</div>
		<div class="row skype-details">
			<div class="span3 pull-right">
				<img src="/assets/skype.png">
				<div class="mail-id"><a href="mailto:mobby@mobbyart.com" title="">mobby@mobbyart.com</a></div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</section>

<!-- <section class="contact-us">
	<div class="container">
		<div class="row">
			<div class="span4 left-side">
				<img class="left-mark" src="/assets/left-mark.png">
				<p class="title">Nos encantaría saber de usted</p>
				<p class="sub-title">Por favor, póngase en contacto con nosotros con cualquier pregunta sobre:</p>
				<ul class="">
					<li><img src="/assets/list-tick-gray.png"> &nbsp;diseño</li>
					<li><img src="/assets/list-tick-gray.png"> &nbsp;envío</li>
					<li><img src="/assets/list-tick-gray.png"> &nbsp;Productos</li>
					<li><img src="/assets/list-tick-gray.png"> &nbsp;asociación</li>
					<li><img src="/assets/list-tick-gray.png"> &nbsp;Sugerencias</li>
					<li><img src="/assets/list-tick-gray.png"> &nbsp;Comentarios Comentarios</li>
				</ul>
			</div>
			<div class="span8 right-side">
				<div class="contact-box span6">
					<%= simple_form_for @contact, :url => contact_us_path do |f| %>
					<img src="/assets/send-msg-corner.png" class="corner">
					<div class="title">Envíenos un mensaje</div>
					<div class="underline"></div>
					<%= f.text_field :name, :class=>"name", :placeholder =>"Ingrese su Nombre" %>
					<%= f.text_field :email, :class=>"email", :placeholder =>"Ingrese su E-mail" %>
					<%= f.text_area :message, :class=>"message", :placeholder =>"Ingrese el mensaje" %>
					<div class="follow-us">
						<a class="social-gplus" href="#"></a>
						<a class="social-fb" href="#"></a>
						<%= f.button :submit, :class=>"btn btn-danger pull-right", :value=>"Enviar mensaje" %>
					</div>
						<a class="twitter-contact" href="#"><img src="/assets/twitter-contact.png"></a>

					<% end %>
				</div>
			</div>
		</div>
		<div class="row skype-details">
			<div class="span3 pull-right">
				<img src="/assets/skype.png">
				<div class="mail-id"><a href="mailto:mobby@mobbyart.com" title="">mobby@mobbyart.com</a></div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</section> -->

app/views/home/terms_and_conditions.html.erb
<%=raw t(:terms_and_conditions_content) %>

app/views/home/user_settings.html.erb
<%= stylesheet_link_tag "user_settings",:media=>"all" %>
<%= javascript_include_tag "jquery-validation" %>
<section class="user-settings">
	<div class="container">
		<div class="row">
			<div class="span12">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#profile" data-target="#profile" data-toggle="tab">Profile</a>
					</li>
					<li class=""><a href="#change_pass" data-target="#change_pass" data-toggle="tab">Change Password</a>
						<li class=""><a href="#billing" data-target="#billing" data-toggle="tab">Billing Address</a>
						</li>
						<li class=""><a href="#shipping" data-target="#shipping" data-toggle="tab">Shipping Address</a>
						</li>
						<li class=""><a href="#design" data-target="#design" data-toggle="tab">Own Designs</a>
						</li>
						<li class=""><a href="#order" data-target="#order" data-toggle="tab">Order Details</a>
						</li>
					</ul>

					<div class="tab-content">
						<div class="tab-pane active fade in" id="profile">
							<%= simple_form_for @user, :url => save_user_path do |f| %>
							<%= f.input :email %><span class='error user_email_check hide-element'>Enter the Valid Email</span>
							<%= f.input :first_name %>
							<%= f.input :last_name %>
							<%= f.input :mobile %>
							<%= f.button :submit, "Update",:class => "btn btn-info" %>
							<% end %>
						</div>
						<div class="tab-pane" id="change_pass">
							<%= simple_form_for @user, :url => change_password_path do |f| %>
							<%= f.input :password %>
							<%= f.input :password_confirmation,:label=> "Confirm Password" %>
							<%= f.button :submit, "Change Password",:class => "btn btn-info" %>
							<% end %>
						</div>
						<div class="tab-pane" id="billing">
							<%= simple_form_for @billing, :url => profile_billing_path() do |f| %>
							<%= f.input :first_name %>
							<%= f.input :last_name %>
							<%= f.input :address1 %>
							<%= f.input :address2 %>
							<%= f.input :city %>
							<%= f.input :state %>
							<%= f.input :country %>
							<%= f.input :postal_code %>
							<%= f.button :submit, "Update",:class => "btn btn-info"  %>
							<% end %>
						</div>
						<div class="tab-pane" id="shipping">
							<%= simple_form_for @shipping, :url => profile_shipping_path() do |f| %>
							<%= f.input :first_name %>
							<%= f.input :last_name %>
							<%= f.input :address1 %>
							<%= f.input :address2 %>
							<%= f.input :city %>
							<%= f.input :state %>
							<%= f.input :country %>
							<%= f.input :postal_code %>
							<%= f.button :submit, "Update",:class => "btn btn-info"  %>
							<% end %>
						</div>
						<div class="tab-pane" id="design">
							<div class="product-list">
								<div class="all-products">
									<%@user_items.each do |item|%>
									<div class="product">
										<div class="full-details hide">
											<div class="close-full">X</div>
											<div class="left">
												<div class="title">
													<%=item.title%>
												</div>
												<div class="images">
													<img class="image" src="<%=item.image.url%>"/>
													<img class="image1" src="<%=item.image1.url%>"/>
												</div>
											</div>
											<div class="right">
												<div class="title">Notes :</div>
												<div class="design_notes">
													<%=item.design_notes%>
												</div>
												<a href="/delete_user_product/<%=item.id%>" class="btn btn-danger">Delete</a>
											</div>
											<div class="date-time">
												<div class="title">Date & Time</div>
												<%= raw item.created_at.strftime("<span>Designed</span> on %m/%d/%Y <span>at</span> %I:%M%p")%>
												<%= raw item.updated_at.strftime("<span>Last Update</span> on %m/%d/%Y <span>at</span> %I:%M%p")%>
											</div>
										</div>
										<div class="less-details">
											<div class="title">
												<%=item.title%>
											</div>
											<div class="images">
												<img class="image" src="<%=item.image.url%>"/>
											</div>
										</div>
									</div>
									<% end %>
								</div>
							</div>
						</div>
						<div class="tab-pane" id="order"></div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<div class="current_email hide"><%= current_user.email %></div>
	<script type="text/javascript">
		$(document).ready(function(){
			$(".user_email_check").insertAfter("#user_email")		
			$(document).on("click",".less-details",function(){
				$(".all-products").prepend($(this).closest(".product"));
				$(".close-full").each(function(){
					$(this).trigger("click")
				});
				$(this).hide();
				$(this).siblings().show(500);
				return false;
			});

			$(document).on("click",".close-full",function(){
				$(this).closest(".full-details").hide(500);
				$(this).closest(".product").find(".less-details").show(500);
				return false;
			});

			$(document).on("click","#change_pass input[type=submit]",function(){
				if($("#change_pass form").valid())
					return true
				else
					return false
			});
			$(document).on("click","#profile input[type=submit]",function(){
				var pattern = new RegExp(/^[+a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i);
				email = pattern.test($("#user_email").val());
				if($("#user_email").val() != $(".current_email").html()){
					if(email)
					{
						$.ajax({
							type: "get",
							url: '/email_avail.json',
							async: false,
							data: {"email" : $("#user_email").val()},
							success: function (data) {
								console.log(data.msg)
								if(data.msg != ""){
									$(".user_email_check").text(data.msg).show();
									can_return = false
								}
								else{
									$(".user_email_check").hide();
									can_return = true
								}
							}
						});
						return can_return
					}
					else{
						$(".user_email_check").text("Enter the valid Email").show();
						$(".user_email_check").show();
						return false
					}
				}
			});
			$("#change_pass form").validate({
				errorElement: "span",
				highlight: function (element, errorClass) {
					$(element).removeClass('error');
				},
				rules: {
					"user[password]": {
						'required' : true,
						minlength: 8
					},
					"user[password_confirmation]": {
						'required' : true,
						'equalTo' : "#user_password"
					}
				},
				messages: {
					"user[password]": {
						'required' : "Enter the Password",
						'minlength' : "Enter atleast 8 characters"
					},
					"user[password_confirmation]": {
						'required' : "Enter the Confirm Password",
						'equalTo' : "Password did not match"
					}
				}    
			});
		});
</script>